spring.application.name=ControlPelotillegue

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#spring.datasource.url=jdbc:postgresql://localhost:5432/estacionamientoPelotillegue
#spring.datasource.username=postgres
#spring.datasource.password=nueva_contrasena
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.jsp
