spring.application.name=Demo_JPA
server.port=9090
#Acceder a los jsp
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

#crear o actualizar tablas
spring.jpa.hibernate.ddl-auto=update
#para mostrar las query por consola
spring.jpa.show-sql= true
#configuracion del datasource postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/desafio
spring.datasource.username=postgres
spring.datasource.password=nueva_contrasena